-- Prisma migration 0002_relax_progress_completed_check
-- F3 fix (approved solution A): relax chk_progress_completed_after_start so a
-- legitimate completion can never fail on app/DB clock skew (observed: 3ms).
-- started_at is generated by the database clock while completed_at is supplied
-- by the application clock; the previous strict >= comparison rejected valid
-- completions whenever the app clock lagged behind by even 1ms.
-- The relaxed form keeps the original intent (completed_at must not absurdly
-- precede started_at) with a 5-minute tolerance for clock skew.
-- The constraint NAME is unchanged, so prisma/schema.prisma needs no edit and
-- no drift is introduced. No data is modified; all existing rows satisfy this.
-- 0001 is left untouched; siraj_complement.sql remains the frozen mirror of 0001.

ALTER TABLE student_course_progress DROP CONSTRAINT chk_progress_completed_after_start;
ALTER TABLE student_course_progress ADD CONSTRAINT chk_progress_completed_after_start
  CHECK (completed_at IS NULL OR completed_at >= started_at - INTERVAL '5 minutes');
